name: 'Create Version Properties'
description: 'Creates version.properties file from GitHub Variables'

runs:
  using: "composite"
  steps:
    - name: Create version properties
      shell: bash
      run: |
        cat > version.properties << EOF
        VERSION_CODE=${{ vars.VERSION_CODE }}
        VERSION_MAJOR=${{ vars.VERSION_MAJOR }}
        VERSION_MINOR=${{ vars.VERSION_MINOR }}
        VERSION_PATCH=${{ vars.VERSION_PATCH }}
        EOF