name: 'Create Version Properties'
description: 'Creates version.properties file from GitHub Variables'

inputs:
  version_code:
    description: 'Version code'
    required: true
  version_major:
    description: 'Major version number'
    required: true
  version_minor:
    description: 'Minor version number'
    required: true
  version_patch:
    description: 'Patch version number'
    required: true
runs:
  using: "composite"
  steps:
    - name: Create version properties
      shell: bash
      run: |
        cat > version.properties << EOF
        VERSION_CODE=${{ inputs.version_code }}
        VERSION_MAJOR=${{ inputs.version_major }}
        VERSION_MINOR=${{ inputs.version_minor }}
        VERSION_PATCH=${{ inputs.version_patch }}
        EOF