name: Build Version Verification

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Create version properties
        run: |
          cat > version.properties << EOF
          VERSION_CODE=${{ vars.VERSION_CODE }}
          VERSION_MAJOR=${{ vars.VERSION_MAJOR }}
          VERSION_MINOR=${{ vars.VERSION_MINOR }}
          VERSION_PATCH=${{ vars.VERSION_PATCH }}
          EOF
      
      - name: Build with Gradle
        run: ./gradlew build